### ISSUE TITLE
Error in setting up and running the server

### ISSUE THREAD

**Issue by nagarjun063** [servo-ai/servo-platform#3]
after cloning and setting up the requirements as per the documentation, when i give npm run server,i get the following error:
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server@0.5.0 dev: `concurrently --kill-others  "npm run editor-serve" "npm run server"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the server@0.5.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by lmessinger** [comment]
you might need to install concurrently. I've updated the readme. thanks!
